### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by PerMildner** [sebastianbenz/eclipse-task-editor#38]
This was while editing/viewing a largish (malformed) that used to be a plain text file which makes the task editor somewhat confused. (But note that this was after several other exceptions from the task editor.)

(As always with OOME the real cause may not be on the stack trace)

java.lang.OutOfMemoryError: Java heap space
    at org.eclipse.ui.internal.views.markers.MarkerContentGenerator.internalGatherMarkers(MarkerContentGenerator.java:1072)
    at org.eclipse.ui.internal.views.markers.MarkerContentGenerator.gatherMarkers(MarkerContentGenerator.java:1013)
    at org.eclipse.ui.internal.views.markers.MarkerContentGenerator.generateMarkerEntries(MarkerContentGenerator.java:991)
    at org.eclipse.ui.internal.views.markers.MarkerUpdateJob.clean(MarkerUpdateJob.java:117)
    at org.eclipse.ui.internal.views.markers.MarkerUpdateJob.buildMarkers(MarkerUpdateJob.java:77)
    at org.eclipse.ui.internal.views.markers.MarkerUpdateJob.run(MarkerUpdateJob.java:57)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by sebastianbenz** [comment]
How big was the file and what was your Xmx setting? I will try to reproduce the problem.

**Comment by PerMildner** [comment]
about 153,670  bytes

eclipse.vmargs=-Xms40m -Xmx512m
